config/routes.rb
Checkpoint::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    resources :periods, :only => :index
    get :all_periods, :controller => :periods, :action => :all_periods
  end

  resources :permissions,   :except => [:show, :edit, :update]

  resources :subdivisions,  :only   => [:index, :show] do
    resources :periods, :only => []  do
      resources :groups, :only => [:show]
    end
    resources :lecturers, :only => [:index] do
      resources :permissions, :only => [:new, :create, :destroy], :controller => :lecturer_permissions
    end
    resources :dockets, :except => [:destroy, :new, :create] do
      post :import, :on => :member
    end
  end

  resources :users,         :only   => [:index] do
    get :search, :on => :collection
  end

  resources :periods do
    post :import, :on => :member
    post :add_group, :on => :member
    resources :groups, :only => [:destroy, :show], :controller => :period_groups do
      resources :dockets, :except => [:index], :controller => :period_dockets
    end
  end
  resources :lecturers,     :only   => [:show] do
    resources :dockets, :except => [:destroy, :new, :create], :controller => :lecturer_dockets
  end

  mount CheckpointAPI => '/'

  root :to => 'application#index'
end

app/models/period.rb
class Period < ActiveRecord::Base
  extend Enumerize
  attr_accessible :ends_at, :kind, :starts_at, :season_type, :graduate

  has_many :dockets, :dependent => :destroy
  has_many :groups, :dependent => :destroy
  has_many :students, :through => :groups
  has_many :lecturers, ->{ uniq  } ,  :through => :dockets

  default_scope { order('id DESC') }
  scope :semester,        ->                       { where('kind = :kind1 OR kind = :kind2', :kind1 => :kt_1, :kind2 => :kt_2)}
  scope :closed_sessions, ->                       { where('kind = :kind and ends_at < :date', :kind => :exam_session, :date => Time.zone.today) }
  scope :closed_kts,      ->                       { where('kind in (:kind) and ends_at < :date', :kind => [:kt_1, :kt_2], :date => Time.zone.today) }
  scope :actual,          ->                       { where('ends_at >= ?', Time.zone.today + 1) }
  scope :closed,          ->                       { where('ends_at < ?', Time.zone.today + 1) }
  scope :for_subdivision, ->(subdivision)          { joins(:dockets).where('dockets.subdivision_id = ?', subdivision.id).uniq }
  scope :for_lecturer,    ->(lecturer)             { joins(:dockets).where('dockets.lecturer_id = ?', lecturer.id).uniq }
  scope :by_kind,         ->(kind ,season, year)   { where('kind = :kind and season_type = :season_type and starts_at between :start_of_year and :end_of_year',
                                                     :kind => kind, :season_type => season, :start_of_year => "#{year}-01-01".to_date, :end_of_year => "#{year}-12-31".to_date) }
  scope :by_year,         ->(year)                 { where('starts_at between :start_of_year and :end_of_year',
                                                     :start_of_year => "#{year}-01-01".to_date, :end_of_year => "#{year}-12-31".to_date) }

  enumerize :kind, :in => [:kt_1, :kt_2, :exam_session], :predicates => true
  enumerize :season_type, :in => [:spring, :autumn], :predicates => true

  def to_s
    "#{title} #{timescale}"
  end

  def actual?
    return true if Time.zone.today <= self.ends_at + 1
    false
  end

  def editable?
    Time.zone.today >= starts_at && Time.zone.today <= ends_at
  end

  def not_session?
    return true if self.kt_1? || self.kt_2?
    false
  end

  def not_for_last_course?
    return true if (self.kt_2? && self.autumn?) || self.spring? || (self.exam_session? && !self.graduate)
    false
  end

  def year
    self.starts_at.strftime('%Y')
  end

  def timescale
    "с #{self.starts_at.strftime('%d.%m.%Y')} по #{self.ends_at.strftime('%d.%m.%Y')}"
  end

  def docket_path
    "public/grades/#{year}/#{self.season_type}/#{self.kind}_#{self.id}"
  end

  def json_path
    "public/files/api/#{year}/#{self.season_type}/"
  end

  def json_url
    "#{Settings[:app][:url]}/files/api/#{year}/#{self.season_type}/period_#{id}.json"
  end

  def title
    "".tap do |s|
      s << "#{self.season_type_text} #{year}, #{self.kind_text.try(:mb_chars).try(:downcase)}"
      s << ', 5 курс' if self.graduate
    end
  end

  def kind_order
    return 1 if kind == 'kt_1'
    return 2 if kind == 'kt_2'
    return 3 if kind == 'exam_session'
  end
end

app/controllers/api/periods_controller.rb
class Api::PeriodsController < ApplicationController
  respond_to :json, :only => :index

  def index
    @periods = Period.closed_sessions
    respond_with(@periods) do |format|
      format.json { render :json => @periods.to_json(:only => [:id], :methods => [:json_url]) }
    end
  end

  def all_periods
    @periods = Period.closed
    respond_with(@periods) do |format|
      format.json { render :json => @periods.to_json(:only => [:id], :methods => [:json_url]) }
    end
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  inherit_resources
  load_and_authorize_resource
  actions :all
  custom_actions :resource => [:import, :add_group]

  def import
    import!{
      flash[:notice] = 'Генерация ведомостей запущена в фоновом режиме'

      ImportWorker.perform_async(@period.id, params['import']['group_pattern'])

      redirect_to @period and return
    }
  end

  def add_group
    add_group!{
      flash[:notice] = 'Группа добавлена'
      GroupInit.new(@period, params['add_group']['group_number'], nil).prepare_group
      redirect_to @period and return
    }
  end
end

app/views/periods/_form.html.erb
<%= simple_form_for @period do |f| %>
  <%= f.input :starts_at %>
  <%= f.input :ends_at %>
  <%= f.input :kind %>
  <%= f.input :season_type %>
  <%= f.submit 'Создать' %>
<% end %>

app/views/periods/edit.html.erb
<%= render 'form' %>

app/views/periods/index.html.erb
<%= link_to "Добавить период", new_period_path %>
<ul class="list periods">
  <% @periods.each do |period| %>
    <li>
      <%= link_to "#{period.title}. #{period.timescale}", period %>
      <div>
        <span class='groups'><%= I18n.t(:groups, :count => period.groups.count) %>, </span>
        <span class='dockets'><%= I18n.t(:dockets, :count => period.dockets.count) %>, </span>
        <span class='filled_dockets'>заполнено <%= I18n.t(:dockets, :count => (period.dockets.count - period.dockets.unfilled.count)) %></span>
      </div>
    </li>
  <% end %>
</ul>

app/views/periods/new.html.erb
<%= render 'form' %>

app/views/periods/show.html.erb
<div class='breadcrumbs'>
  <ul>
    <li>
      <%= link_to "Все периоды", periods_path %>
    </li>
  </ul>
</div>

<h1><%= "#{@period.title} #{@period.timescale}" %></h1>

<div class='info'>Укажите патерн номером групп для загрузки ведомостей</div>
<%= simple_form_for :import, url: import_period_path(@period) do |f| %>
  <%= f.input_field :group_pattern %>
  <%= f.submit 'Загрузить' %>
<% end %>

<div class='info'>Или добавьте группу вручную</div>
<%= simple_form_for :add_group, :url => add_group_period_path(@period) do |f| %>
  <%= f.input_field :group_number, :placeholder => 'Укажите номер группы' %>
  <%= f.submit 'Добавить группу' %>
<% end %>

<div class='info'><%= I18n.t(:groups, :count => @period.groups.count) %></div>
<div class='info'><%= I18n.t(:dockets, :count => @period.dockets.count) %></div>
<div class='info'><%= I18n.t(:dockets, :count => @period.dockets.count - @period.dockets.unfilled.count) %> заполнено</div>


<div class="actions">
  <%= link_to "Редактировать", edit_period_path(@period) %>
</div>

<div class='search'>
  <div class='search_in_list_wrapper'>
    <%= simple_form_for :search, :html => { :class => 'search_form' } do |f| %>
      <%= f.input :query, :label => false, :placeholder => 'поиск', :input_html => { :data => { :list => '.list.groups' } } %>
    <% end %>
  </div>
</div>

<ul class="list groups">
  <% @period.groups.order(:title).each do |group| %>
    <li class='info'>
      <div class='info'><%= link_to group, period_group_path(@period, group) %></div>
      <%= content_tag :span, 'в группе нет студентов', :class => 'error' if group.students.empty? %>
      <%= content_tag :span, I18n.t(:students, :count => group.students.count) if group.students.any? %>
      <span class='dockets'><%= I18n.t(:dockets, :count => group.dockets.count) %>, </span>
      <span class='filled_dockets'>заполнено <%= I18n.t(:dockets, :count => group.dockets.count - group.dockets.unfilled.uniq.count) %></span>
      <div class="actions">
        <%= link_to "Удалить", period_group_path(@period, group), :method => :delete, :confirm => 'Вы уверены?' %>
      </div>
      <hr />
    </li>
  <% end %>
</ul>