config/routes.rb
Checkpoint::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    resources :periods, :only => :index
    get :all_periods, :controller => :periods, :action => :all_periods
  end

  resources :permissions,   :except => [:show, :edit, :update]

  resources :subdivisions,  :only   => [:index, :show] do
    resources :periods, :only => []  do
      resources :groups, :only => [:show]
    end
    resources :lecturers, :only => [:index] do
      resources :permissions, :only => [:new, :create, :destroy], :controller => :lecturer_permissions
    end
    resources :dockets, :except => [:destroy, :new, :create] do
      post :import, :on => :member
    end
  end

  resources :users,         :only   => [:index] do
    get :search, :on => :collection
  end

  resources :periods do
    post :import, :on => :member
    post :add_group, :on => :member
    resources :groups, :only => [:destroy, :show], :controller => :period_groups do
      resources :dockets, :except => [:index], :controller => :period_dockets
    end
  end
  resources :lecturers,     :only   => [:show] do
    resources :dockets, :except => [:destroy, :new, :create], :controller => :lecturer_dockets
  end

  mount CheckpointAPI => '/'

  root :to => 'application#index'
end

app/models/subdivision.rb
class Subdivision < ActiveRecord::Base
  attr_accessible :abbr, :title, :folder_name

  has_many :dockets, :dependent => :destroy
  has_many :permissions, :as => :context
  has_many :lecturers, :through => :dockets, :uniq => true

  scope :by_abbr, ->(_) { order(:abbr) }
  scope :by_title, ->(_) { order(:title) }

  after_create :set_folder_name

  def to_s
    title || abbr
  end

  def set_folder_name
    self.folder_name = SecureRandom.hex(15)
    save!
  end

  def abbr_translit
    Russian.translit(abbr)
  end

  def dockets_count(period)
    self.dockets.by_period(period).with_active_grades.uniq.count
  end
end

app/models/subdivision/chair.rb
class Subdivision::Chair < Subdivision
  has_many :groups
end

app/models/subdivision/faculty.rb
class Subdivision::Faculty < Subdivision
  has_many :groups
end

app/controllers/subdivisions_controller.rb
class SubdivisionsController < ApplicationController
  inherit_resources
  load_and_authorize_resource
  actions :index, :show
  has_scope :by_title, :default => 1

  def show
    show!{
      @groups = @subdivision.groups
      @periods_with_groups = GroupsByCourses.new(@subdivision).group
      @periods = Period.for_subdivision(@subdivision)
    }
  end
end

app/views/subdivisions/_item.html.erb
<li>
  <div class='info'>
    <%= link_to "#{period.title}", subdivision_dockets_path(@subdivision, :by_period => period.id) %>
    <% if summary_dockets_links(period).any? %>
      <div class='links_to_file'>
        <%= link_to 'Скачать', '#', :class => 'download' %>
        <ul class='links'>
          <%= summary_dockets_links(period).join("\n").html_safe %>
        </ul>
      </div>
    <% end %>
    (<%= period.timescale %>)
  </div>
  <% if @subdivision.dockets.by_period(period.id).unfilled.any? %>
    <span class='filled_dockets'>
      не заполнено
      <%= I18n.t(:dockets, :count => @subdivision.dockets.by_period(period.id).unfilled.count) %> из
      <%= @subdivision.dockets.by_period(period.id).count %>
    </span>
  <% else %>
      все ведомости заполнены
  <% end %>
</li>

app/views/subdivisions/index.html.erb
<div class='breadcrumbs'>
  <ul>
    <li>
      <span>Список обеспечивающих кафедр</span>
    </li>
  </ul>
</div>

<div class='search'>
  <div class='search_in_list_wrapper'>
    <%= simple_form_for :search, :html => { :class => 'search_form' } do |f| %>
      <%= f.input :query,
        :label => false,
        :placeholder => 'Найти по названию кафедры/факультета, ФИО ответственного, адресу почты',
        :input_html => { :data => { :list => '.list.subdivisions' } } %>
    <% end %>
  </div>

</div>


<ul class='list subdivisions'>
  <% @subdivisions.each do |subdivision| %>
    <li>
      <%= link_to subdivision, subdivision_path(subdivision) %>
      (<%= subdivision.permissions.any? ? subdivision.permissions.map(&:title).join(',').html_safe : "<span class='alert'>ответственный не назначен</span>".html_safe %>)
    </li>
  <% end %>
</ul>

app/views/subdivisions/show.html.erb
<div class='breadcrumbs'>
  <ul>
    <%= render :partial => 'application/subdivisions_breadcrumbs' %>
    <li>
      <span><%= @subdivision %></span>
    </li>
  </ul>
</div>

<h1><%= @subdivision %></h1>

<%= link_to "Список преподавателей", subdivision_lecturers_path(@subdivision) unless @subdivision.title.match(/факультет/i) %>

<%= render :partial => 'application/warning' %>

<h2>Периоды</h2>

<div class='periods_list'>
  <ul class='list periods actual'>
    <% @periods.actual.each do |period| %>
      <%= render :partial => 'item', :locals => { :period => period } %>
    <% end %>
  </ul>
  <%= link_to_if @periods.closed.any?, "Архив", '#', :class => 'archive toggle_down' %>
  <ul class="list periods closed">
    <% @periods.closed.each do |period| %>
      <%= render :partial => 'item', :locals => { :period => period } %>
    <% end %>
  </ul>
</div>

<% if @periods_with_groups.any? %>
  <h2>Группы</h2>
<% end %>

<div class='groups_list'>
  <% @periods_with_groups.each do |course, groups| %>
    <span class="course_title"><%= course %> курс</span>
    <ul class="groups <%= course %>_course">
      <% groups.each do |group| %>
        <li>
        <%= link_to group.title, subdivision_period_group_path(@subdivision, Group.newest_period_for(group.title), group.title) %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>