config/routes.rb
Checkpoint::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    resources :periods, :only => :index
    get :all_periods, :controller => :periods, :action => :all_periods
  end

  resources :permissions,   :except => [:show, :edit, :update]

  resources :subdivisions,  :only   => [:index, :show] do
    resources :periods, :only => []  do
      resources :groups, :only => [:show]
    end
    resources :lecturers, :only => [:index] do
      resources :permissions, :only => [:new, :create, :destroy], :controller => :lecturer_permissions
    end
    resources :dockets, :except => [:destroy, :new, :create] do
      post :import, :on => :member
    end
  end

  resources :users,         :only   => [:index] do
    get :search, :on => :collection
  end

  resources :periods do
    post :import, :on => :member
    post :add_group, :on => :member
    resources :groups, :only => [:destroy, :show], :controller => :period_groups do
      resources :dockets, :except => [:index], :controller => :period_dockets
    end
  end
  resources :lecturers,     :only   => [:show] do
    resources :dockets, :except => [:destroy, :new, :create], :controller => :lecturer_dockets
  end

  mount CheckpointAPI => '/'

  root :to => 'application#index'
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :title, :course, :period_id, :faculty_id, :chair_id

  has_many :students, :dependent => :destroy
  has_many :dockets, :dependent => :destroy

  belongs_to :chair,   :class_name => 'Subdivision::Chair'
  belongs_to :faculty, :class_name => 'Subdivision::Faculty'
  belongs_to :period
  delegate :kind_order, :to => :period

  alias_attribute :to_s, :title
  alias_attribute :contingent_number, :title

  scope :ordered,   -> { order(:title)}
  scope :by_period_desc, -> { order('period_id DESC') }
  scope :by_period_asc, -> { order('period_id ASC') }

  CONTINGENT_GROUP_NUMBERS = {
    '012-М1' => '012М/1',
    '012-М2' => '012М/2',
    '013М-1' => '013-М1',
    '163-M' => '163-М',
    '143-M'  => '143-М',
    '1A3'    => '1А3',
    '369-1'  => '369',
    '842-1'  => '842',
    '843-М'  => '843-м',
    '873-М'  => '873-м',
    '922-C'  => '922-с',
    '034-1M' => '034-М1',
    '034-2M' => '034-М2',
    '213' => '213-1',
    '223' => '223-1',
    '543-М' => '543-м'
  }

  def contingent_number
    CONTINGENT_GROUP_NUMBERS[title] || title
  end

  def translited_title
    Russian.translit(self.title).gsub(/\//, '')
  end

  def self.newest_period_for(title)
    #where(:title => title).by_period_desc.first.period
    where(:title => title).sort_by(&:kind_order).last.period
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  inherit_resources
  defaults :finder => :find_by_title
  load_and_authorize_resource
  belongs_to :period
  actions :show

  def show
    show! do |format|
      @subdivision = Subdivision.find(params[:subdivision_id])
      @periods = GroupPeriods.new(@group, @period, @subdivision)
      @consolidated_table = ConsolidatedTable.new(@group)
      format.html

      format.pdf do
        pdf_file = ConsolidatedExport.new(@period, @group)
        send_data pdf_file.render,
                   :type => 'text/pdf; charset=cp1251; header=present',
                   :disposition => 'attachment',
                   :filename => pdf_file.filename and return
      end

      format.xlsx do
        xlsx_file = XlsExport.new(@period, @group)
        send_data xlsx_file.render.string,
                   :type => 'text/xlsx; charset=cp1251; header=present',
                   :disposition => 'attachment',
                   :filename => xlsx_file.filename and return
      end
    end
  end
end

app/views/groups/show.html.erb
<div class='breadcrumbs'>
  <ul>
    <%= render :partial => 'application/subdivisions_breadcrumbs' %>
    <li>
      <span><%= link_to @subdivision, subdivision_path(@subdivision) %></span>
    </li>
    <li>
      <span>Группа <%= @group.title %>, <%= @period.title %></span>
    </li>
  </ul>
</div>

<div class='period_title'>
  <h2>Группа <%= @group.title %>, <%= @period.title %></h2>
</div>

<div class="period_navigation">
  <% if @periods.prev %>
    <%= link_to "&larr;".html_safe, subdivision_period_group_path(@subdivision, @periods.prev, @group.title), :class => 'button' %>
  <% else %>
    <span class="button disabled">&larr;</span>
  <% end %>
  <span class='go-to-select'>
    <%= select_tag :period, options_for_select(@periods.titles_with_urls, subdivision_period_group_url(@subdivision, @period, @group.title)), :include_blank => false, :class => 'select' %>
  </span>
  <% if @periods.next %>
    <%= link_to "&rarr;".html_safe, subdivision_period_group_path(@subdivision, @periods.next, @group.title), :class => 'button' %>
  <% else %>
    <span class="button disabled">&rarr;</span>
  <% end %>
  <div class="download_link">
    <%= link_to "Скачать PDF", subdivision_period_group_path(@subdivision, @period, @group.title, :format => :pdf) %>
    <%= link_to "Скачать XLSX", subdivision_period_group_path(@subdivision, @period, @group.title, :format => :xlsx) %>
  </div>
</div>

<div class='tables'>
  <div class="consolidated_table table_1">
    <table>
    <thead>
      <tr>
        <td class='number'>№</td>
        <td>ФИО Студента</td>
      </tr>
    </thead>
    <tbody>
      <% @consolidated_table.student_dockets_hash.each_with_index do |student, index| %>
        <tr>
          <td class='number'><%= index + 1 %></td>
          <td class='name'><%= student[:student].abbreviated_name %></td>
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>
  <div class='consolidated_table table_2'>
    <table>
    <thead>
      <tr>
        <% @consolidated_table.docket_disciplines.each do |d| %>
          <% if can?(:edit, d) %>
            <td><%= link_to d.discipline, subdivision_docket_path(d.subdivision, d) %></td>
          <% else %>
              <td><%= d.discipline %></td>
          <% end %>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @consolidated_table.student_dockets_hash.each_with_index do |student, index| %>
        <tr>
          <% student[:dockets].each do |docket| %>
            <td class='grade'><%= docket[:grades][:kt_1].to_s %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>
</div>