config/routes.rb
Checkpoint::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    resources :periods, :only => :index
    get :all_periods, :controller => :periods, :action => :all_periods
  end

  resources :permissions,   :except => [:show, :edit, :update]

  resources :subdivisions,  :only   => [:index, :show] do
    resources :periods, :only => []  do
      resources :groups, :only => [:show]
    end
    resources :lecturers, :only => [:index] do
      resources :permissions, :only => [:new, :create, :destroy], :controller => :lecturer_permissions
    end
    resources :dockets, :except => [:destroy, :new, :create] do
      post :import, :on => :member
    end
  end

  resources :users,         :only   => [:index] do
    get :search, :on => :collection
  end

  resources :periods do
    post :import, :on => :member
    post :add_group, :on => :member
    resources :groups, :only => [:destroy, :show], :controller => :period_groups do
      resources :dockets, :except => [:index], :controller => :period_dockets
    end
  end
  resources :lecturers,     :only   => [:show] do
    resources :dockets, :except => [:destroy, :new, :create], :controller => :lecturer_dockets
  end

  mount CheckpointAPI => '/'

  root :to => 'application#index'
end

app/controllers/lecturer_dockets_controller.rb
class LecturerDocketsController < ApplicationController
  inherit_resources
  defaults :resource_class => Docket, :collection_name => 'dockets', :instance_name => 'docket', :route_instance_name => 'docket'
  belongs_to :lecturer
  actions :all, :except => [:destroy, :new, :create]
  has_scope :by_period
  load_and_authorize_resource :except => [:index]

  def index
    index!{
      @period = Period.find(params[:by_period])
      authorize! :show, @period
    }
  end

end

app/views/lecturer_dockets/edit.html.erb
<div class='breadcrumbs'>
  <ul>
    <li>
      <%= link_to @lecturer, lecturer_path(@lecturer) %>
    </li>
    <li>
      <%= link_to @docket.period.title, lecturer_dockets_path(@lecturer, :by_period => @docket.period.id) %>
    </li>
    <li>
      <%= link_to "Ведомость по предмету &laquo;#{@docket}&raquo;".html_safe, lecturer_docket_path(@lecturer, @docket) %>
    </li>
  </ul>
</div>

<%= render 'dockets/form' %>

app/views/lecturer_dockets/index.html.erb
<div class='breadcrumbs'>
  <ul>
    <li>
      <%= link_to @lecturer, lecturer_path(@lecturer) %>
    </li>
    <li>
      <%= link_to @period.title, lecturer_dockets_path(@lecturer, :by_period => @period.id) %>
    </li>
  </ul>
</div>

<h1>Список ведомостей</h1>

<div class='search'>
  <div class='search_in_list_wrapper'>
    <%= simple_form_for :search do |f| %>
      <%= f.input :query, :label => false, :placeholder => 'поиск ведомости', :input_html => { :data => { :list => '.list.dockets' } } %>
    <% end %>
  </div>
</div>

<ul class='list dockets'>
  <% @dockets.each do |docket| %>
    <li>
      <%= link_to [docket.discipline, "гр. #{docket.group}", docket.lecturer, (docket.kind_text.mb_chars.downcase if docket.kind)].compact.join(', '), [@lecturer, docket] %>
      <div class="errors">
        <span><%= 'не заполнена ведомость' unless docket.filled? %></span>
      </div>
    </li>
  <% end %>
</ul>

app/views/lecturer_dockets/show.html.erb
<div class='breadcrumbs'>
  <ul>
    <li>
      <%= link_to @lecturer, lecturer_path(@lecturer) %>
    </li>
    <li>
      <%= link_to @docket.period.title, lecturer_dockets_path(@lecturer, :by_period => @docket.period.id) %>
    </li>
  </ul>
</div>

<h1>Ведомость по предмету &laquo;<%= @docket %>&raquo;</h1>

<div class="actions">
  <%= link_to "Редактировать", edit_lecturer_docket_path(@lecturer, @docket) if can? :edit, @docket %>
</div>

<div class='info'>Преподаватель: <%= @docket.lecturer || 'Не указано' %></div>
<div class='info'>Группа: <%= @docket.group %></div>

<%= render @docket %>